#!/usr/bin/env python3
"""Embed assets/ and lang/ into the launcher binary.

    python3 tools/embed.py <source dir> <output .c>

Each file becomes a byte array. Text and TrueType files are deflated (raw
zlib stream, decompressed once at startup with miniz); PNG and JPEG are
already compressed and are stored as they are. An index maps the relative
path to the bytes, so the code asks for "fonts/ss3-400.ttf" and never for a
symbol name.
"""
import os
import sys
import zlib

src, out = sys.argv[1], sys.argv[2]
files = []
for top in ("assets", "lang"):
    base = os.path.join(src, top)
    for dirpath, _, names in os.walk(base):
        for n in sorted(names):
            if n.startswith(".") or n.endswith((".md", ".txt", ".kra", ".svg")):
                continue
            full = os.path.join(dirpath, n)
            rel = os.path.relpath(full, src).replace(os.sep, "/")
            if rel.startswith("assets/"):
                rel = rel[len("assets/"):]
            files.append((rel, full))
files.sort()

os.makedirs(os.path.dirname(out), exist_ok=True)
with open(out, "w", encoding="ascii") as f:
    f.write("/* GENERATED by tools/embed.py. */\n#include <stddef.h>\n\n")
    index = []
    for i, (rel, full) in enumerate(files):
        data = open(full, "rb").read()
        packed = not rel.endswith((".png", ".jpg"))
        blob = zlib.compress(data, 9) if packed else data
        f.write(f"static const unsigned char a{i}[{len(blob)}] = {{")
        for j, b in enumerate(blob):
            if j % 32 == 0:
                f.write("\n")
            f.write(f"{b},")
        f.write("\n};\n")
        index.append((rel, i, len(blob), len(data), 1 if packed else 0))
    f.write("\nstruct unifico_asset { const char* path; const unsigned char* data; size_t size; size_t raw; int deflated; };\n")
    f.write("const struct unifico_asset unifico_assets[] = {\n")
    for rel, i, size, raw, packed in index:
        f.write(f'    {{"{rel}", a{i}, {size}, {raw}, {packed}}},\n')
    f.write("    {0, 0, 0, 0, 0}\n};\n")
print(f"embedded {len(files)} assets")
